### ISSUE TITLE
Moving Sage gets triggered multiple times

### ISSUE THREAD

**Issue by Ojka91** [Arkk92/element-front#29]
Sometimes, when surrounded by multiple elements, when you try to move the sage it triggers the same movement multiple times.

The first movement succeed, the rest of them fail for obvious reasons. This does not affect the gameplay, but it triggers an error message that the player can see.
![movesagebug](https://github.com/user-attachments/assets/50a2ebe9-72af-49d8-9fbc-f218a9e03042)

**Comment by Ojka91** [comment]
You can see in the logging section (bottom left) that sage movement is not valid message appear multiple times when moving sometimes 
![image](https://github.com/user-attachments/assets/79dbd01b-a266-4206-9c38-c40eacf8c702)


If you want to see the logs on the shared image you need to add them in the frontend part

**Comment by Arkk92** [comment]
@Ojka91 the Frontend is gatewaying what's coming from the backend here. From frontend point of view, this error is populated from GameController.movePlayerSage which is related to backend and never used in frontend.
If you want me to help you out in the investigative, please to provide the steps required to make this error trigger so I can debug it from the Frontend.

**Comment by Ojka91** [comment]
@Arkk92 the frontend is sending movement multiple times on one single click. 
That's the reason you see multiple 'Sage movement is not valid' responses from `GameController.movePlayerSage`

You can add logs here https://github.com/Arkk92/element-front/blob/89c77b252368ed13da0017e0659df027f6dbda81/element-front/src/composables/PlayerMenu/PlacementUtils.ts#L45 on the client side, so you will be able to see the same results as the first GIF shared

You will see how when clicking to move the sage, it runs this code `SocketInstance.emit("moveSage", data);`multiple times
