### ISSUE TITLE
Unable to access team.expensify Gmail 

### ISSUE THREAD

**Issue by Casian-P** [Arkk92/element-front#63]
![Screenshot 2024-10-02 132559](https://github.com/user-attachments/assets/f895d67f-8f14-49bf-ac79-07fb51fca347)

I am no longer able to access my team.expensify Gmail wich is casian.pantilimon@team.expensify.com. Since today I am getting the above error.

I have tried to: 
- sign in from a different browser 
- clear cache and cookies 
- reset my password 
- the issue still persists with the same error

**Comment by Arkk92** [comment]
Dear @Casian-P ,
I think this isn't the correct place for this question. If you have any issue with Google accounts you should open the issue in the Google support forums. This repository has nothing related to Google.
